mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: localhost
    port: 1883
    keepalive: 60
  private_path: device/001
serializer: json:dumps
deserializer: json:loads
bridge:
  #tagFull
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: Augbot.msg:tagFull
    topic_from: /tagFull
    topic_to: tagFull
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: Augbot.msg:tagFull
    topic_from: tagFull
    topic_to: /tagFull_output
  #least_squares
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: Augbot.msg:position
    topic_from: /least_squares
    topic_to: least_squares
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: Augbot.msg:position
    topic_from: least_squares
    topic_to: /least_squares_output
  #decawave position
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: Augbot.msg:position
    topic_from: /dwm1001
    topic_to: dwm1001
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: Augbot.msg:position
    topic_from: dwm1001
    topic_to: /dwm1001_output