uwb_simulation:
  noise:
    mu: 0.1
    sigma: 0.1
  nAnchors: 5
  anchors: [
    [ -5.0, -5.0, 2.0 ],
    [ 5.0, 5.0, 2.0 ],
    [ 5.0, -5.0, 2.0 ],
    [ -5.0, 5.0, 2.0 ],
    [ 0.0, 0.0, 2.0 ]
  ]
