topics2rosbag:
  type: "replay"
  topics:
  #[ROStopic, message type]
    [
#      [ "anchorConfig", anchorConfig ],
[ "leastSquares", position ],
[ "leastSquaresMA", position ],
[ "UWB", tagFull ],
[ "deadReckoning", position ],
[ "deadReckoningSP", position ],
[ "deadReckoningACC", position ],
[ "imu", Imu],
[ "synchPoints", synchPoint],
#
#
[ "microbit", orientation],
[ "synchPointError", synchPointError]
#[ "pipico", orientation]
#
#
     # [ "/mqtt_leastSquares", position ],
     # [ "/mqtt_tagFull", tagFull ],
     # [ "/mqtt_deadReckoning", position ]

    ]
