topics2rosbag:
  type: "real"
  topics:
    [
#      [ "anchorConfig", anchorConfig ],
[ "least_squares", position ],
[ "localization", tagFull ],
[ "deadReckoning", position ],
[ "deadReckoning1", position ],
[ "deadReckoning2", position ],
[ "deadReckoning3", position ],
[ "imu", Imu],
[ "synchPoints", synchPoint],
#
#
[ "microbit", orientation]
#[ "pipico", orientation]
#
#
     # [ "/mqtt_least_squares", position ],
     # [ "/mqtt_tagFull", tagFull ],
     # [ "/mqtt_deadReckoning", position ]

    ]
