topics2rosbag:
  type: "real"
  topics:
    [
#      [ "anchorConfig", anchorConfig ],
[ "leastSquares", position ],
[ "leastSquaresMA", position ],
[ "UWB", tagFull ],
[ "deadReckoning", position ],
[ "deadReckoning1", position ],
[ "deadReckoning2", position ],
[ "deadReckoning3", position ],
[ "imu", Imu],
[ "synchPoints", synchPoint],
#
#
[ "microbit", orientation],
[ "synchPointError", synchPointError]
#[ "pipico", orientation]
#
#
     # [ "/mqtt_leastSquares", position ],
     # [ "/mqtt_tagFull", tagFull ],
     # [ "/mqtt_deadReckoning", position ]

    ]
