topics2rosbag:
  topics:
    [
      [ "anchorConfig", anchorConfig ],
      [ "least_squares", position ],
      [ "localization", tagFull ],
      [ "deadReckoning", position ]  
#,
     # [ "imu", Imu"]

     # [ "/mqtt_least_squares", position ],
     # [ "/mqtt_tagFull", tagFull ],
     # [ "/mqtt_deadReckoning", position ]

    ]
