topics2rosbag:
  topics:
    [
      [ "anchorConfig", anchorConfig ],
      [ "least_squares", position ],
      [ "localization", tagFull ],
      [ "deadReckoning", position ] #,
   #   [ "deadReckoning1", position ]
    ]
